apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: bene-web-route
spec:
  http:
    - name: bene-web
      match:
        paths:
          - /*
        hosts:
          - justbene.com
          - www.justbene.com
      backends:
        - serviceName: bene-web
          servicePort: 80
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
