bases:
  - ../base/

namespace: bene-development

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ingress.yaml

configMapGenerator:
  - name: cm-bene-web-config
    files:
      - env
